-- MySQL Script generated by MySQL Workbench
-- Tue Nov  4 09:55:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `contraseña` VARCHAR(45) NOT NULL,
  `rol_usu` VARCHAR(15) NOT NULL,
  `nombre_usu` VARCHAR(25) NOT NULL,
  `correo_usu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_cat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_prod` VARCHAR(45) NOT NULL,
  `fecha_expiracion` DATETIME NOT NULL,
  `stock` INT NOT NULL,
  `CATEGORIA_id_categoria` INT NOT NULL,
  `USUARIO_id_usuario` INT NOT NULL,
  `lote_producto` BIGINT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_PRODUCTO_CATEGORIA1_idx` (`CATEGORIA_id_categoria` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_USUARIO1_idx` (`USUARIO_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_id_categoria`)
    REFERENCES `mydb`.`CATEGORIA` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_USUARIO1`
    FOREIGN KEY (`USUARIO_id_usuario`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROVEEDOR` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre_prov` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_PROVEEDOR_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_PROVEEDOR_PRODUCTO` (
  `precio_unitario` DECIMAL NOT NULL,
  `PRODUCTO_id_producto` INT NOT NULL,
  `PROVEEDOR_id_proveedor` INT NOT NULL,
  INDEX `fk_AUTOR_PRODUCTO1_idx` (`PRODUCTO_id_producto` ASC) VISIBLE,
  INDEX `fk_AUTOR_PROVEEDOR1_idx` (`PROVEEDOR_id_proveedor` ASC) VISIBLE,
  PRIMARY KEY (`precio_unitario`),
  CONSTRAINT `fk_AUTOR_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUTOR_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_id_proveedor`)
    REFERENCES `mydb`.`PROVEEDOR` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPO_MOVIMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_MOVIMIENTO` (
  `id_tipo_movimiento` INT NOT NULL AUTO_INCREMENT,
  `nombre_movimiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_movimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MOVIMIENTO_PROD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MOVIMIENTO_PROD` (
  `id_movimiento_inv` BIGINT(100) NOT NULL AUTO_INCREMENT,
  `fecha_movimiento` DATETIME NOT NULL,
  `cantidad_desplazada` INT NOT NULL,
  `motivo_repor` VARCHAR(45) NOT NULL,
  `picker_checker` INT NOT NULL,
  `PRODUCTO_id_producto` INT NOT NULL,
  `USUARIO_id_usuario` INT NOT NULL,
  `TIPO_MOVIMIENTO_id_tipo_movimiento` INT NOT NULL,
  PRIMARY KEY (`id_movimiento_inv`),
  INDEX `fk_MOVIMIENTO_PROD_PRODUCTO1_idx` (`PRODUCTO_id_producto` ASC) VISIBLE,
  INDEX `fk_MOVIMIENTO_PROD_USUARIO1_idx` (`USUARIO_id_usuario` ASC) VISIBLE,
  INDEX `fk_MOVIMIENTO_PROD_TIPO_MOVIMIENTO1_idx` (`TIPO_MOVIMIENTO_id_tipo_movimiento` ASC) VISIBLE,
  CONSTRAINT `fk_MOVIMIENTO_PROD_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOVIMIENTO_PROD_USUARIO1`
    FOREIGN KEY (`USUARIO_id_usuario`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOVIMIENTO_PROD_TIPO_MOVIMIENTO1`
    FOREIGN KEY (`TIPO_MOVIMIENTO_id_tipo_movimiento`)
    REFERENCES `mydb`.`TIPO_MOVIMIENTO` (`id_tipo_movimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALERTA_INV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALERTA_INV` (
  `id_alerta` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NOT NULL,
  `tipo_alerta` VARCHAR(15) NOT NULL,
  `descripcion_alerta` VARCHAR(45) NOT NULL,
  `PRODUCTO_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_alerta`),
  INDEX `fk_ALERTA_INV_PRODUCTO1_idx` (`PRODUCTO_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_ALERTA_INV_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REPORTE_INV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REPORTE_INV` (
  `id_reporte_inv` INT NOT NULL AUTO_INCREMENT,
  `fecha_generacion` DATETIME NULL,
  `tipo_reporte` VARCHAR(15) NOT NULL,
  `MOVIMIENTO_PROD_id_movimiento_inv` INT NOT NULL,
  `ALERTA_INV_id_alerta` INT NOT NULL,
  `USUARIO_id_usuario` INT NOT NULL,
  `url_resultado` VARCHAR(255) NULL,
  PRIMARY KEY (`id_reporte_inv`),
  INDEX `fk_REPORTE_INV_MOVIMIENTO_PROD1_idx` (`MOVIMIENTO_PROD_id_movimiento_inv` ASC) VISIBLE,
  INDEX `fk_REPORTE_INV_ALERTA_INV1_idx` (`ALERTA_INV_id_alerta` ASC) VISIBLE,
  INDEX `fk_REPORTE_INV_USUARIO1_idx` (`USUARIO_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_REPORTE_INV_MOVIMIENTO_PROD1`
    FOREIGN KEY (`MOVIMIENTO_PROD_id_movimiento_inv`)
    REFERENCES `mydb`.`MOVIMIENTO_PROD` (`id_movimiento_inv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REPORTE_INV_ALERTA_INV1`
    FOREIGN KEY (`ALERTA_INV_id_alerta`)
    REFERENCES `mydb`.`ALERTA_INV` (`id_alerta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REPORTE_INV_USUARIO1`
    FOREIGN KEY (`USUARIO_id_usuario`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`METODO_PROYECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`METODO_PROYECCION` (
  `id_metodo_proyeccion` INT NOT NULL AUTO_INCREMENT,
  `nombre_metodo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_metodo_proyeccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPO_PROYECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_PROYECCION` (
  `id_tipo_proyeccion` INT NOT NULL,
  `nombre_proyeccion` VARCHAR(15) NULL,
  PRIMARY KEY (`id_tipo_proyeccion`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`PROYECCIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROYECCIONES` (
  `id_proyecciones` INT NOT NULL AUTO_INCREMENT,
  `resultado_proyeccion` VARCHAR(25) NOT NULL,
  `referencia_tipo` VARCHAR(15) NOT NULL,
  `fecha_generacion` DATETIME NOT NULL,
  `unidad_medida` VARCHAR(30) NOT NULL,
  `METODO_PROYECCION_id_metodo_proyeccion` INT NOT NULL,
  `TIPO_PROYECCION_id_tipo_proyeccion` INT NOT NULL,
  `CATEGORIA_id_categoria` INT NOT NULL,
  `PRODUCTO_id_producto` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NULL,
  PRIMARY KEY (`id_proyecciones`),
  INDEX `fk_PROYECCIONES_METODO_PROYECCION1_idx` (`METODO_PROYECCION_id_metodo_proyeccion` ASC) VISIBLE,
  INDEX `fk_PROYECCIONES_TIPO_PROYECCION1_idx` (`TIPO_PROYECCION_id_tipo_proyeccion` ASC) VISIBLE,
  INDEX `fk_PROYECCIONES_CATEGORIA1_idx` (`CATEGORIA_id_categoria` ASC) VISIBLE,
  INDEX `fk_PROYECCIONES_PRODUCTO1_idx` (`PRODUCTO_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_PROYECCIONES_METODO_PROYECCION1`
    FOREIGN KEY (`METODO_PROYECCION_id_metodo_proyeccion`)
    REFERENCES `mydb`.`METODO_PROYECCION` (`id_metodo_proyeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROYECCIONES_TIPO_PROYECCION1`
    FOREIGN KEY (`TIPO_PROYECCION_id_tipo_proyeccion`)
    REFERENCES `mydb`.`TIPO_PROYECCION` (`id_tipo_proyeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROYECCIONES_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_id_categoria`)
    REFERENCES `mydb`.`CATEGORIA` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROYECCIONES_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTADO_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTADO_PEDIDO` (
  `id_estado pedido` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(15) NOT NULL,
  `descripcion_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO_COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO_COMPRA` (
  `id_pedido` INT NOT NULL,
  `fecha_pedido` DATETIME NOT NULL,
  `total_pedido` DECIMAL NOT NULL,
  `ESTADO_PEDIDO_id_estado pedido` INT NOT NULL AUTO_INCREMENT,
  `PROVEEDOR_id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_PEDIDO_COMPRA_ESTADO_PEDIDO1_idx` (`ESTADO_PEDIDO_id_estado pedido` ASC) VISIBLE,
  INDEX `fk_PEDIDO_COMPRA_PROVEEDOR1_idx` (`PROVEEDOR_id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_COMPRA_ESTADO_PEDIDO1`
    FOREIGN KEY (`ESTADO_PEDIDO_id_estado pedido`)
    REFERENCES `mydb`.`ESTADO_PEDIDO` (`id_estado pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_COMPRA_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_id_proveedor`)
    REFERENCES `mydb`.`PROVEEDOR` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_PEDIDO` (
  `id_detalle_pedido` BIGINT(100) NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `subtotal` DECIMAL NOT NULL,
  `precio_unitario` DOUBLE NOT NULL,
  `PEDIDO_COMPRA_id_pedido` INT NOT NULL,
  `PRODUCTO_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_detalle_pedido`),
  INDEX `fk_DETALLE_PEDIDO_PEDIDO_COMPRA1_idx` (`PEDIDO_COMPRA_id_pedido` ASC) VISIBLE,
  INDEX `fk_DETALLE_PEDIDO_PRODUCTO1_idx` (`PRODUCTO_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_PEDIDO_PEDIDO_COMPRA1`
    FOREIGN KEY (`PEDIDO_COMPRA_id_pedido`)
    REFERENCES `mydb`.`PEDIDO_COMPRA` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_PEDIDO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `identificacion_cliente` BIGINT NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENTA_REGISTRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENTA_REGISTRO` (
  `id_venta` BIGINT NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATETIME NULL,
  `Total_venta` DECIMAL NULL,
  `CLIENTE_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_VENTA_REGISTRO_CLIENTE1_idx` (`CLIENTE_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_VENTA_REGISTRO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_id_cliente`)
    REFERENCES `mydb`.`CLIENTE` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_VENTA` (
  `id_detalle_venta` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL NOT NULL,
  `PRODUCTO_id_producto` INT NOT NULL,
  `VENTA_REGISTRO_id_venta` INT NOT NULL,
  PRIMARY KEY (`id_detalle_venta`),
  INDEX `fk_DETALLE_VENTA_PRODUCTO1_idx` (`PRODUCTO_id_producto` ASC) VISIBLE,
  INDEX `fk_DETALLE_VENTA_VENTA_REGISTRO1_idx` (`VENTA_REGISTRO_id_venta` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_VENTA_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_VENTA_VENTA_REGISTRO1`
    FOREIGN KEY (`VENTA_REGISTRO_id_venta`)
    REFERENCES `mydb`.`VENTA_REGISTRO` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '						';


-- -----------------------------------------------------
-- Table `mydb`.`FILTRO_BUSQUEDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FILTRO_BUSQUEDA` (
  `id_filtro_ busqueda` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `REPORTE_INV_id_reporte_inv` INT NOT NULL,
  PRIMARY KEY (`id_filtro_ busqueda`),
  INDEX `fk_FILTRO_BUSQUEDA_REPORTE_INV1_idx` (`REPORTE_INV_id_reporte_inv` ASC) VISIBLE,
  CONSTRAINT `fk_FILTRO_BUSQUEDA_REPORTE_INV1`
    FOREIGN KEY (`REPORTE_INV_id_reporte_inv`)
    REFERENCES `mydb`.`REPORTE_INV` (`id_reporte_inv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETALLE_FILTRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETALLE_FILTRO` (
  `id_detalle_filtro` INT NOT NULL AUTO_INCREMENT,
  `tipo_dato` VARCHAR(20) NULL,
  `campo_filtro` VARCHAR(50) NULL,
  `valor_filtro` VARCHAR(255) NULL,
  `FILTRO_BUSQUEDA_id_filtro_ busqueda` INT NOT NULL,
  PRIMARY KEY (`id_detalle_filtro`),
  INDEX `fk_DETALLE_FILTRO_FILTRO_BUSQUEDA1_idx` (`FILTRO_BUSQUEDA_id_filtro_ busqueda` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_FILTRO_FILTRO_BUSQUEDA1`
    FOREIGN KEY (`FILTRO_BUSQUEDA_id_filtro_ busqueda`)
    REFERENCES `mydb`.`FILTRO_BUSQUEDA` (`id_filtro_ busqueda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPO_DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_DIRECCION` (
  `id_tipo_direccion` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(20) NULL,
  PRIMARY KEY (`id_tipo_direccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BARRIO_DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BARRIO_DIRECCION` (
  `id_barrio` INT NOT NULL AUTO_INCREMENT,
  `nombre_barrio` VARCHAR(30) NULL,
  PRIMARY KEY (`id_barrio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DIRECCION` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(50) NULL,
  `complemento` VARCHAR(45) NULL,
  `TIPO_DIRECCION_id_tipo_direccion` INT NOT NULL,
  `BARRIO_DIRECCION_id_barrio` INT NOT NULL,
  `CLIENTE_id_cliente` INT NOT NULL,
  `PROVEEDOR_id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `fk_DIRECCION_TIPO_DIRECCION1_idx` (`TIPO_DIRECCION_id_tipo_direccion` ASC) VISIBLE,
  INDEX `fk_DIRECCION_BARRIO_DIRECCION1_idx` (`BARRIO_DIRECCION_id_barrio` ASC) VISIBLE,
  INDEX `fk_DIRECCION_CLIENTE1_idx` (`CLIENTE_id_cliente` ASC) VISIBLE,
  INDEX `fk_DIRECCION_PROVEEDOR1_idx` (`PROVEEDOR_id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_DIRECCION_TIPO_DIRECCION1`
    FOREIGN KEY (`TIPO_DIRECCION_id_tipo_direccion`)
    REFERENCES `mydb`.`TIPO_DIRECCION` (`id_tipo_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIRECCION_BARRIO_DIRECCION1`
    FOREIGN KEY (`BARRIO_DIRECCION_id_barrio`)
    REFERENCES `mydb`.`BARRIO_DIRECCION` (`id_barrio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIRECCION_CLIENTE1`
    FOREIGN KEY (`CLIENTE_id_cliente`)
    REFERENCES `mydb`.`CLIENTE` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIRECCION_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_id_proveedor`)
    REFERENCES `mydb`.`PROVEEDOR` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPO_CORREO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_CORREO` (
  `id_tipo_correo` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_tipo_correo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CORREO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CORREO` (
  `id_correo` INT NOT NULL AUTO_INCREMENT,
  `correo_electronico` VARCHAR(45) NOT NULL,
  `TIPO_CORREO_id_tipo_correo` INT NOT NULL,
  `CLIENTE_id_cliente` INT NOT NULL,
  `PROVEEDOR_id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_correo`),
  INDEX `fk_CORREO_TIPO_CORREO1_idx` (`TIPO_CORREO_id_tipo_correo` ASC) VISIBLE,
  INDEX `fk_CORREO_CLIENTE1_idx` (`CLIENTE_id_cliente` ASC) VISIBLE,
  INDEX `fk_CORREO_PROVEEDOR1_idx` (`PROVEEDOR_id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_CORREO_TIPO_CORREO1`
    FOREIGN KEY (`TIPO_CORREO_id_tipo_correo`)
    REFERENCES `mydb`.`TIPO_CORREO` (`id_tipo_correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CORREO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_id_cliente`)
    REFERENCES `mydb`.`CLIENTE` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CORREO_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_id_proveedor`)
    REFERENCES `mydb`.`PROVEEDOR` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPO_TELEFONO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_TELEFONO` (
  `id_tipo_telefono` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_tipo_telefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TELEFONO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TELEFONO` (
  `id_telefono` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `TIPO_TELEFONO_id_tipo_telefono` INT NOT NULL,
  `CLIENTE_id_cliente` INT NOT NULL,
  `PROVEEDOR_id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_telefono`),
  INDEX `fk_TELEFONO_TIPO_TELEFONO1_idx` (`TIPO_TELEFONO_id_tipo_telefono` ASC) VISIBLE,
  INDEX `fk_TELEFONO_CLIENTE1_idx` (`CLIENTE_id_cliente` ASC) VISIBLE,
  INDEX `fk_TELEFONO_PROVEEDOR1_idx` (`PROVEEDOR_id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFONO_TIPO_TELEFONO1`
    FOREIGN KEY (`TIPO_TELEFONO_id_tipo_telefono`)
    REFERENCES `mydb`.`TIPO_TELEFONO` (`id_tipo_telefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TELEFONO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_id_cliente`)
    REFERENCES `mydb`.`CLIENTE` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TELEFONO_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_id_proveedor`)
    REFERENCES `mydb`.`PROVEEDOR` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPO_ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_ESTADO` (
  `id_tipo_estado` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTADO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTADO_USUARIO` (
  `id_estado_usuario` INT NOT NULL AUTO_INCREMENT,
  `observacion` VARCHAR(45) NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `TIPO_ESTADO_id_tipo_estado` INT NOT NULL,
  `USUARIO_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_estado_usuario`),
  INDEX `fk_ESTADO_USUARIO_TIPO_ESTADO1_idx` (`TIPO_ESTADO_id_tipo_estado` ASC) VISIBLE,
  INDEX `fk_ESTADO_USUARIO_USUARIO1_idx` (`USUARIO_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_ESTADO_USUARIO_TIPO_ESTADO1`
    FOREIGN KEY (`TIPO_ESTADO_id_tipo_estado`)
    REFERENCES `mydb`.`TIPO_ESTADO` (`id_tipo_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTADO_USUARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_id_usuario`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
